/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from './app.component.css.shim.ngstyle';
import * as i1 from '@angular/core';
import * as i2 from './navigation/navigation.component.ngfactory';
import * as i3 from '../../../src/app/navigation/navigation.component';
import * as i4 from '../../../src/app/app.component';
const styles_AppComponent:any[] = [i0.styles];
export const RenderType_AppComponent:i1.RendererType2 = i1.ɵcrt({encapsulation:0,styles:styles_AppComponent,
    data:{'animation':[{type:7,name:'flyInOut',definitions:[{type:1,expr:'void=>*',
        animation:[{type:6,styles:{transform:'translateX(-100%)'},offset:(null as any)},
            {type:4,styles:{type:6,styles:{transform:'rotate(180deg)'},offset:(null as any)},
                timings:'2s 3s ease-in'}],options:(null as any)},{type:1,expr:'void=>*',
        animation:[{type:6,styles:{transform:'translateX(-100%)'},offset:(null as any)}],
        options:(null as any)}],options:{}}]}});
export function View_AppComponent_0(_l:any):i1.ɵViewDefinition {
  return i1.ɵvid(0,[(_l()(),i1.ɵted((null as any),['\n'])),(_l()(),i1.ɵted((null as any),
      ['\n'])),(_l()(),i1.ɵeld(0,(null as any),(null as any),1,'app-navigation',([] as any[]),
      (null as any),(null as any),(null as any),i2.View_NavigationComponent_0,i2.RenderType_NavigationComponent)),
      i1.ɵdid(114688,(null as any),0,i3.NavigationComponent,([] as any[]),(null as any),
          (null as any)),(_l()(),i1.ɵted((null as any),['\n']))],(_ck,_v) => {
    _ck(_v,3,0);
  },(null as any));
}
export function View_AppComponent_Host_0(_l:any):i1.ɵViewDefinition {
  return i1.ɵvid(0,[(_l()(),i1.ɵeld(0,(null as any),(null as any),1,'app-root',([] as any[]),
      (null as any),(null as any),(null as any),View_AppComponent_0,RenderType_AppComponent)),
      i1.ɵdid(49152,(null as any),0,i4.AppComponent,([] as any[]),(null as any),(null as any))],
      (null as any),(null as any));
}
export const AppComponentNgFactory:i1.ComponentFactory<i4.AppComponent> = i1.ɵccf('app-root',
    i4.AppComponent,View_AppComponent_Host_0,{},{},([] as any[]));
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiL1VzZXJzL3NocnV0aW5hbGxhcmkvUHJvZmlsZS9TYWlQcm9maWxlL3NyYy9hcHAvYXBwLmNvbXBvbmVudC5uZ2ZhY3RvcnkudHMiLCJ2ZXJzaW9uIjozLCJzb3VyY2VSb290IjoiIiwic291cmNlcyI6WyJuZzovLy9Vc2Vycy9zaHJ1dGluYWxsYXJpL1Byb2ZpbGUvU2FpUHJvZmlsZS9zcmMvYXBwL2FwcC5jb21wb25lbnQudHMiLCJuZzovLy9Vc2Vycy9zaHJ1dGluYWxsYXJpL1Byb2ZpbGUvU2FpUHJvZmlsZS9zcmMvYXBwL2FwcC5jb21wb25lbnQuaHRtbCIsIm5nOi8vL1VzZXJzL3NocnV0aW5hbGxhcmkvUHJvZmlsZS9TYWlQcm9maWxlL3NyYy9hcHAvYXBwLmNvbXBvbmVudC50cy5BcHBDb21wb25lbnRfSG9zdC5odG1sIl0sInNvdXJjZXNDb250ZW50IjpbIiAiLCJcbjwhLS1UaGUgd2hvbGUgY29udGVudCBiZWxvdyBjYW4gYmUgcmVtb3ZlZCB3aXRoIHRoZSBuZXcgY29kZS4tLT5cbjxhcHAtbmF2aWdhdGlvbj48L2FwcC1uYXZpZ2F0aW9uPlxuIiwiPGFwcC1yb290PjwvYXBwLXJvb3Q+Il0sIm1hcHBpbmdzIjoiQUFBQTs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7OztvQkNBQSx1Q0FDZ0U7TUFBQSxTQUNoRTtNQUFBO2FBQUE7VUFBQSxlQUFpQztJQUFqQzs7OztvQkNGQTtNQUFBO2FBQUE7Ozs7In0=
