/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


export const styles:any[] = ['.intro[_ngcontent-%COMP%]{\nbackground-color: #87CEEB;\nfont-family: Verdana, Geneva, sans-serif;\nfont-size: 12pt;\ntext-align: center;\n}\n.image[_ngcontent-%COMP%]{\n	background-color: #808080;\n}'];
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiL1VzZXJzL3NocnV0aW5hbGxhcmkvUHJvZmlsZS9TYWlQcm9maWxlL3NyYy9hcHAvaW50cm9kdWN0aW9uL2ludHJvZHVjdGlvbi5jb21wb25lbnQuY3NzLnNoaW0ubmdzdHlsZS50cyIsInZlcnNpb24iOjMsInNvdXJjZVJvb3QiOiIiLCJzb3VyY2VzIjpbIm5nOi8vL1VzZXJzL3NocnV0aW5hbGxhcmkvUHJvZmlsZS9TYWlQcm9maWxlL3NyYy9hcHAvaW50cm9kdWN0aW9uL2ludHJvZHVjdGlvbi5jb21wb25lbnQuY3NzIl0sInNvdXJjZXNDb250ZW50IjpbIiAiXSwibWFwcGluZ3MiOiJBQUFBOzs7Ozs7OzsifQ==
