/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from './introduction.component.css.shim.ngstyle';
import * as i1 from '@angular/core';
import * as i2 from '../../../node_modules/@angular/material/typings/index.ngfactory';
import * as i3 from '@angular/material';
import * as i4 from '../../../../src/app/services/introduction.service';
import * as i5 from 'angularfire2/database';
import * as i6 from '../../../../src/app/introduction/introduction.component';
const styles_IntroductionComponent:any[] = [i0.styles];
export const RenderType_IntroductionComponent:i1.RendererType2 = i1.ɵcrt({encapsulation:0,
    styles:styles_IntroductionComponent,data:{'animation':[{type:7,name:'flyInOut',
        definitions:[{type:1,expr:'void=>*',animation:[{type:6,styles:{transform:'translateX(-100%)'},
            offset:(null as any)},{type:4,styles:{type:6,styles:{transform:'rotate(180deg)'},
            offset:(null as any)},timings:'2s 3s ease-in'}],options:(null as any)},
            {type:1,expr:'*=>void',animation:[{type:6,styles:{transform:'translateX(-100%)'},
                offset:(null as any)}],options:(null as any)}],options:{}}]}});
export function View_IntroductionComponent_0(_l:any):i1.ɵViewDefinition {
  return i1.ɵvid(0,[(_l()(),i1.ɵeld(0,(null as any),(null as any),16,'md-card',[['class',
      'intro mat-card']],[[24,'@flyInOut',0]],(null as any),(null as any),i2.View_MdCard_0,
      i2.RenderType_MdCard)),i1.ɵdid(16384,(null as any),0,i3.MdPrefixRejector,[[2,
      i3.MATERIAL_COMPATIBILITY_MODE],i1.ElementRef],(null as any),(null as any)),
      i1.ɵdid(49152,(null as any),0,i3.MdCard,([] as any[]),(null as any),(null as any)),
      (_l()(),i1.ɵted(0,[' '])),(_l()(),i1.ɵeld(0,(null as any),0,3,'md-card-title',
          [['class','mat-card-title']],(null as any),(null as any),(null as any),(null as any),
          (null as any))),i1.ɵdid(16384,(null as any),0,i3.MdPrefixRejector,[[2,i3.MATERIAL_COMPATIBILITY_MODE],
          i1.ElementRef],(null as any),(null as any)),i1.ɵdid(16384,(null as any),
          0,i3.MdCardTitle,([] as any[]),(null as any),(null as any)),(_l()(),i1.ɵted((null as any),
          ['\n'])),(_l()(),i1.ɵted(0,[' '])),(_l()(),i1.ɵeld(0,(null as any),0,1,'img',
          [['alt','Photo of a Shiba Inu'],['class','image mat-card-image'],['height',
              '500'],['md-card-image',''],['src','assets/img/sai.jpg'],['width','100%']],
          (null as any),(null as any),(null as any),(null as any),(null as any))),
      i1.ɵdid(16384,(null as any),0,i3.MdCardImage,([] as any[]),(null as any),(null as any)),
      (_l()(),i1.ɵted(0,[' '])),(_l()(),i1.ɵeld(0,(null as any),0,3,'md-card-content',
          [['class','mat-card-content']],(null as any),(null as any),(null as any),
          (null as any),(null as any))),i1.ɵdid(16384,(null as any),0,i3.MdPrefixRejector,
          [[2,i3.MATERIAL_COMPATIBILITY_MODE],i1.ElementRef],(null as any),(null as any)),
      i1.ɵdid(16384,(null as any),0,i3.MdCardContent,([] as any[]),(null as any),(null as any)),
      (_l()(),i1.ɵted((null as any),['\n'])),(_l()(),i1.ɵted(0,[' ']))],(null as any),
      (_ck,_v) => {
        const currVal_0:any = (undefined as any);
        _ck(_v,0,0,currVal_0);
      });
}
export function View_IntroductionComponent_Host_0(_l:any):i1.ɵViewDefinition {
  return i1.ɵvid(0,[(_l()(),i1.ɵeld(0,(null as any),(null as any),2,'app-introduction',
      ([] as any[]),(null as any),(null as any),(null as any),View_IntroductionComponent_0,
      RenderType_IntroductionComponent)),i1.ɵprd(512,(null as any),i4.IntroductionService,
      i4.IntroductionService,[i5.AngularFireDatabase]),i1.ɵdid(114688,(null as any),
      0,i6.IntroductionComponent,[i4.IntroductionService],(null as any),(null as any))],
      (_ck,_v) => {
        _ck(_v,2,0);
      },(null as any));
}
export const IntroductionComponentNgFactory:i1.ComponentFactory<i6.IntroductionComponent> = i1.ɵccf('app-introduction',
    i6.IntroductionComponent,View_IntroductionComponent_Host_0,{},{},([] as any[]));
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiL1VzZXJzL3NocnV0aW5hbGxhcmkvUHJvZmlsZS9TYWlQcm9maWxlL3NyYy9hcHAvaW50cm9kdWN0aW9uL2ludHJvZHVjdGlvbi5jb21wb25lbnQubmdmYWN0b3J5LnRzIiwidmVyc2lvbiI6Mywic291cmNlUm9vdCI6IiIsInNvdXJjZXMiOlsibmc6Ly8vVXNlcnMvc2hydXRpbmFsbGFyaS9Qcm9maWxlL1NhaVByb2ZpbGUvc3JjL2FwcC9pbnRyb2R1Y3Rpb24vaW50cm9kdWN0aW9uLmNvbXBvbmVudC50cyIsIm5nOi8vL1VzZXJzL3NocnV0aW5hbGxhcmkvUHJvZmlsZS9TYWlQcm9maWxlL3NyYy9hcHAvaW50cm9kdWN0aW9uL2ludHJvZHVjdGlvbi5jb21wb25lbnQuaHRtbCIsIm5nOi8vL1VzZXJzL3NocnV0aW5hbGxhcmkvUHJvZmlsZS9TYWlQcm9maWxlL3NyYy9hcHAvaW50cm9kdWN0aW9uL2ludHJvZHVjdGlvbi5jb21wb25lbnQudHMuSW50cm9kdWN0aW9uQ29tcG9uZW50X0hvc3QuaHRtbCJdLCJzb3VyY2VzQ29udGVudCI6WyIgIiwiPG1kLWNhcmQgY2xhc3M9XCJpbnRyb1wiIFtAZmx5SW5PdXRdPiA8bWQtY2FyZC10aXRsZT5cbjwvbWQtY2FyZC10aXRsZT4gPGltZyBtZC1jYXJkLWltYWdlIGNsYXNzPSBpbWFnZSBzcmM9XCJhc3NldHMvaW1nL3NhaS5qcGdcIlxuXHRhbHQ9XCJQaG90byBvZiBhIFNoaWJhIEludVwiIHdpZHRoPTEwMCUgaGVpZ2h0PTUwMD4gPG1kLWNhcmQtY29udGVudD5cbjwvbWQtY2FyZC1jb250ZW50PiA8L21kLWNhcmQ+IiwiPGFwcC1pbnRyb2R1Y3Rpb24+PC9hcHAtaW50cm9kdWN0aW9uPiJdLCJtYXBwaW5ncyI6IkFBQUE7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7OztvQkNBQTtNQUFBOzBCQUFBLFVBQUE7b0NBQUE7YUFBQTtNQUFtQywwQkFBQztVQUFBO1VBQUEsdUJBQUE7dUJBQUEsc0NBQUE7VUFBQSw0REFBZTtVQUFBLFNBQ25DLDBCQUFDO1VBQUE7Y0FBQTtVQUFBO2FBQUE7TUFDaUMsMEJBQUM7VUFBQTtVQUFBLHFDQUFBO1VBQUE7YUFBQTtNQUFpQix1Q0FDbEQ7O1FBSEs7UUFBdkIsV0FBdUIsU0FBdkI7Ozs7b0JDQUE7TUFBQTtzQ0FBQTs2QkFBQSxpQ0FBQTtNQUFBOztRQUFBOzs7OyJ9
