/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from './summary.component.css.shim.ngstyle';
import * as i1 from '@angular/core';
import * as i2 from '../../../node_modules/@angular/material/typings/index.ngfactory';
import * as i3 from '@angular/material';
import * as i4 from '@angular/common';
import * as i5 from '../../../../src/app/summary/summary.component';
import * as i6 from '../../../../src/app/services/introduction.service';
import * as i7 from 'angularfire2/database';
const styles_SummaryComponent:any[] = [i0.styles];
export const RenderType_SummaryComponent:i1.RendererType2 = i1.ɵcrt({encapsulation:0,
    styles:styles_SummaryComponent,data:{'animation':[{type:7,name:'flyInOut',definitions:[{type:1,
        expr:'void=>*',animation:[{type:6,styles:{transform:'translateX(-100%)'},offset:(null as any)},
            {type:4,styles:{type:6,styles:{transform:'rotate(180deg)'},offset:(null as any)},
                timings:'2s 3s ease-in'}],options:(null as any)},{type:1,expr:'void=>*',
        animation:[{type:6,styles:{transform:'translateX(-100%)'},offset:(null as any)}],
        options:(null as any)}],options:{}}]}});
function View_SummaryComponent_1(_l:any):i1.ɵViewDefinition {
  return i1.ɵvid(0,[(_l()(),i1.ɵeld(0,(null as any),(null as any),1,'li',([] as any[]),
      (null as any),(null as any),(null as any),(null as any),(null as any))),(_l()(),
      i1.ɵted((null as any),['\n	','']))],(null as any),(_ck,_v) => {
    const currVal_0:any = _v.context.$implicit.title;
    _ck(_v,1,0,currVal_0);
  });
}
export function View_SummaryComponent_0(_l:any):i1.ɵViewDefinition {
  return i1.ɵvid(0,[(_l()(),i1.ɵted((null as any),['\n'])),(_l()(),i1.ɵeld(0,(null as any),
      (null as any),10,'md-card',[['class','intro mat-card']],[[24,'@flyInOut',0]],
      (null as any),(null as any),i2.View_MdCard_0,i2.RenderType_MdCard)),i1.ɵdid(16384,
      (null as any),0,i3.MdPrefixRejector,[[2,i3.MATERIAL_COMPATIBILITY_MODE],i1.ElementRef],
      (null as any),(null as any)),i1.ɵdid(49152,(null as any),0,i3.MdCard,([] as any[]),
      (null as any),(null as any)),(_l()(),i1.ɵted(0,['\n'])),(_l()(),i1.ɵeld(0,(null as any),
      0,5,'ul',[['class','list']],(null as any),(null as any),(null as any),(null as any),
      (null as any))),(_l()(),i1.ɵted((null as any),['\n	'])),(_l()(),i1.ɵand(16777216,
      (null as any),(null as any),2,(null as any),View_SummaryComponent_1)),i1.ɵdid(802816,
      (null as any),0,i4.NgForOf,[i1.ViewContainerRef,i1.TemplateRef,i1.IterableDiffers],
      {ngForOf:[0,'ngForOf']},(null as any)),i1.ɵpid(131072,i4.AsyncPipe,[i1.ChangeDetectorRef]),
      (_l()(),i1.ɵted((null as any),['\n'])),(_l()(),i1.ɵted(0,['\n'])),(_l()(),i1.ɵted((null as any),
          ['\n\n']))],(_ck,_v) => {
    var _co:i5.SummaryComponent = _v.component;
    const currVal_1:any = i1.ɵunv(_v,8,0,i1.ɵnov(_v,9).transform(_co.items));
    _ck(_v,8,0,currVal_1);
  },(_ck,_v) => {
    const currVal_0:any = (undefined as any);
    _ck(_v,1,0,currVal_0);
  });
}
export function View_SummaryComponent_Host_0(_l:any):i1.ɵViewDefinition {
  return i1.ɵvid(0,[(_l()(),i1.ɵeld(0,(null as any),(null as any),2,'app-summary',
      ([] as any[]),(null as any),(null as any),(null as any),View_SummaryComponent_0,
      RenderType_SummaryComponent)),i1.ɵprd(512,(null as any),i6.IntroductionService,
      i6.IntroductionService,[i7.AngularFireDatabase]),i1.ɵdid(114688,(null as any),
      0,i5.SummaryComponent,[i6.IntroductionService],(null as any),(null as any))],
      (_ck,_v) => {
        _ck(_v,2,0);
      },(null as any));
}
export const SummaryComponentNgFactory:i1.ComponentFactory<i5.SummaryComponent> = i1.ɵccf('app-summary',
    i5.SummaryComponent,View_SummaryComponent_Host_0,{},{},([] as any[]));
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiL1VzZXJzL3NocnV0aW5hbGxhcmkvUHJvZmlsZS9TYWlQcm9maWxlL3NyYy9hcHAvc3VtbWFyeS9zdW1tYXJ5LmNvbXBvbmVudC5uZ2ZhY3RvcnkudHMiLCJ2ZXJzaW9uIjozLCJzb3VyY2VSb290IjoiIiwic291cmNlcyI6WyJuZzovLy9Vc2Vycy9zaHJ1dGluYWxsYXJpL1Byb2ZpbGUvU2FpUHJvZmlsZS9zcmMvYXBwL3N1bW1hcnkvc3VtbWFyeS5jb21wb25lbnQudHMiLCJuZzovLy9Vc2Vycy9zaHJ1dGluYWxsYXJpL1Byb2ZpbGUvU2FpUHJvZmlsZS9zcmMvYXBwL3N1bW1hcnkvc3VtbWFyeS5jb21wb25lbnQuaHRtbCIsIm5nOi8vL1VzZXJzL3NocnV0aW5hbGxhcmkvUHJvZmlsZS9TYWlQcm9maWxlL3NyYy9hcHAvc3VtbWFyeS9zdW1tYXJ5LmNvbXBvbmVudC50cy5TdW1tYXJ5Q29tcG9uZW50X0hvc3QuaHRtbCJdLCJzb3VyY2VzQ29udGVudCI6WyIgIiwiXG48bWQtY2FyZCBjbGFzcz1cImludHJvXCIgW0BmbHlJbk91dF0+XG48dWwgY2xhc3M9XCJsaXN0XCI+XG5cdDxsaSAqbmdGb3I9XCJsZXQgaXRlbSBvZiBpdGVtcyB8IGFzeW5jXCI+XG5cdHt7aXRlbS50aXRsZX19PC9saT5cbjwvdWw+XG48L21kLWNhcmQ+XG5cbiIsIjxhcHAtc3VtbWFyeT48L2FwcC1zdW1tYXJ5PiJdLCJtYXBwaW5ncyI6IkFBQUE7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7b0JDR0M7TUFBQSx3RUFBdUM7YUFBQTtJQUFBO0lBQUE7Ozs7b0JBSHhDLHVDQUNBO01BQUE7TUFBQSwyRUFBQTtNQUFBO01BQUEsb0NBQUE7TUFBQSw2QkFBbUMsMkJBQ25DO01BQUE7TUFBQSxnQkFBaUIsd0NBQ2hCO01BQUEsNkVBQUE7TUFBQTtNQUFBLDhDQUFJO01BQ2UsdUNBQ2YsMkJBQ0s7VUFBQTs7SUFITDtJQUFKLFdBQUksU0FBSjs7SUFGc0I7SUFBdkIsV0FBdUIsU0FBdkI7Ozs7b0JDREE7TUFBQTtpQ0FBQTs2QkFBQSxpQ0FBQTtNQUFBOztRQUFBOzs7OyJ9
