/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


export const styles:any[] = ['.intro[_ngcontent-%COMP%] {\n	background-color: #808080;\n}\n\n.list[_ngcontent-%COMP%] {\n	background-color: #808080;\n	font-family: Verdana, Geneva, sans-serif;\n	font-size: 12pt;\n	color: #FFFFFF;\n	text-align: left;\n}'];
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiL1VzZXJzL3NocnV0aW5hbGxhcmkvUHJvZmlsZS9TYWlQcm9maWxlL3NyYy9hcHAvc3VtbWFyeS9zdW1tYXJ5LmNvbXBvbmVudC5jc3Muc2hpbS5uZ3N0eWxlLnRzIiwidmVyc2lvbiI6Mywic291cmNlUm9vdCI6IiIsInNvdXJjZXMiOlsibmc6Ly8vVXNlcnMvc2hydXRpbmFsbGFyaS9Qcm9maWxlL1NhaVByb2ZpbGUvc3JjL2FwcC9zdW1tYXJ5L3N1bW1hcnkuY29tcG9uZW50LmNzcyJdLCJzb3VyY2VzQ29udGVudCI6WyIgIl0sIm1hcHBpbmdzIjoiQUFBQTs7Ozs7Ozs7In0=
